-- CreateTable
CREATE TABLE "score_ranking" (
    "ID" SERIAL NOT NULL,
    "score" DOUBLE PRECISION NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "score_ranking_pkey" PRIMARY KEY ("ID")
);
